### ISSUE TITLE
SQLITE_ERROR: no such table: user

### ISSUE THREAD

**Issue by AaronNGray** [w3tecch/typeorm-seeding#140]
Getting the following error :-
```
C:\Users\aaron\GitHub\typeorm-seeding>npm run seed:run

> typeorm-seeding@1.6.0 seed:run
> ts-node ./dist/cli.js seed -c sample

🌱  TypeORM Seeding v1.6.0
√ ORM Config loaded
√ Factories are imported
√ Seeders are imported
√ Database connected
\ Executing CreatePets Seeder
❌  Could not save entity
QueryFailedError: SQLITE_ERROR: no such table: user
    at new QueryFailedError (C:\Users\aaron\GitHub\typeorm-seeding\src\error\QueryFailedError.ts:9:9)
    at handler (C:\Users\aaron\GitHub\typeorm-seeding\src\driver\sqlite\SqliteQueryRunner.ts:53:26)
    at Statement.errBack (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\sqlite3\lib\sqlite3.js:16:21) {
  errno: 1,
  code: 'SQLITE_ERROR',
  query: 'INSERT INTO "user"("id", "firstName", "lastName", "middleName", "email", "password") VALUES (?, ?, ?, ?, ?, ?)',
  parameters: [
    '514a585b-52d2-4bd8-8923-48162b073b7b',
    'Tre',
    'Kuvalis',
    null,
    'Tre.Kuvalis2@gmail.com',
    '$2a$10$zgxIjki9vcZJTxP5g5edQuOYHdczzkjG9Aw5ElA9ouFU0teFzPQs2'
  ]
}

❌  Could not make User
Error: Could not save entity
    at EntityFactory.<anonymous> (C:\Users\aaron\GitHub\typeorm-seeding\src\entity-factory.ts:52:15)
    at step (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:139:27)
    at Object.throw (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:120:57)
    at rejected (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:111:69)

❌  Could not save entity
Error: Could not make User
    at EntityFactory.<anonymous> (C:\Users\aaron\GitHub\typeorm-seeding\src\entity-factory.ts:130:19)
    at step (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:139:27)
    at Object.throw (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:120:57)
    at rejected (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:111:69)
× Could not run the seed CreatePets!
Error: Could not save entity
    at EntityFactory.<anonymous> (C:\Users\aaron\GitHub\typeorm-seeding\src\entity-factory.ts:52:15)
    at step (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:139:27)
    at Object.throw (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:120:57)
    at rejected (C:\Users\aaron\GitHub\typeorm-seeding\node_modules\tslib\tslib.js:111:69)
```

**Comment by AaronNGray** [comment]
# Generate Migration
```
ts-node node_modules\typeorm\cli.js migration:generate -n <migration-name>
```
# Seed database
```
ts-node node_modules\typeorm-seeding\dist\cli.js seed
```
# Run migrations
```
ts-node node_modules\typeorm\cli.js migration:run
```
