### ISSUE TITLE
TypeError: Cannot read properties of undefined(reading 'number')

### ISSUE THREAD

**Issue by andi-faizal94** [w3tecch/typeorm-seeding#214]
#edited

I have entity:

![Screen Shot 2022-03-28 at 17 54 28](https://user-images.githubusercontent.com/75654156/160383507-d2deb005-4823-4e7b-bfc7-28c432e1bc90.png)

user.factory.ts

![Screen Shot 2022-03-27 at 22 26 55](https://user-images.githubusercontent.com/75654156/160378825-2bed67fd-6b5c-4953-88dd-9a3f16ee6002.png)

I have problem with file user.factory.ts:

const gender = faker.random.number(1)

To solve my problem i change:

 1. Change column User entity:
 
   @PrimaryGeneratedColumn("uuid")
      id: string;
  
2. Change in user.factory.ts :
- const gender = faker.random.number(1)
- const age = faker.random.number(1)

change with:

  - const gender = faker.random.uuid();
  - const age = faker.random.number({ min: 10, max: 20 });
  
3. Change In Package.json:
 "seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed"

change with:

 "seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js --configName ./ormconfig.json seed"

  this is work to me.
  
  Thank you.

**Comment by jorgebodega** [comment]
Hi! Can you just put some more explicit example, or maybe create a repo to reproduce this? Just because you talked about gender but I cannot see that on entity

**Comment by andi-faizal94** [comment]
> Hi! Can you just put some more explicit example, or maybe create a repo to reproduce this? Just because you talked about gender but I cannot see that on entity

Hi
I'm sorry about it:

my case in Entity:
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from "typeorm";

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  firstName: string;

  @Column()
  lastName: string;

  @Column()
  age: number;

  @Column({ nullable: true })
  addres: string;
}


And I have a file user.factory.ts :

import * as Faker from "faker";
import { define } from "typeorm-seeding";
import { User } from "../../entity/User";

define(User, (faker: typeof Faker) => {
  const gender =  faker.datatype.number(1);
  const firstName = faker.name.firstName(gender);
  const lastName = faker.name.lastName(gender);
  const age = faker.datatype.number(1);
  const addres = faker.random.word();

  const user = new User();
  user.firstName = firstName;
  user.lastName = lastName;
  user.age = age;
  user.addres = addres;
  return user;
});



I fix with :

Change column User entity:
@PrimaryGeneratedColumn("uuid")
id: string;

Change faker.random.number:
const gender = faker.random.uuid();
const age = faker.random.number({ min: 10, max: 20 });
Change In Package.json:
"seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed"
change with:

"seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js --configName ./ormconfig.json seed"

this is work to me.



My Repository:

https://github.com/andi-faizal94/RESTfull-API-TYPEORM-Express-PostgreSQL/blob/main/src/database/factories/user.factory.ts

**Comment by richoandika** [comment]
I got same problem after running the seed
`TypeError: Cannot read properties of undefined (reading 'name')`

**Comment by richoandika** [comment]
> I got same problem after running the seed `TypeError: Cannot read properties of undefined (reading 'name')`
> 
> `"typeorm-seeding": "^1.6.1",`
> 
> ```shell
> PS C:\Users\richoandika\tmp\nestjs> yarn seed:run
> yarn run v1.22.18
> $ ts-node ./node_modules/typeorm-seeding/dist/cli.js seed
> 🌱  TypeORM Seeding v1.6.1
> √ ORM Config loaded
> √ Factories are imported
> √ Seeders are imported
> √ Database connected
> √ Seeder XxxSeed executed
> bin.js seed
> 
> Runs the seeds
> 
> Options:
>   --version         Show version number                                [boolean]
>   -h, --help        Show help                                          [boolean]
>   -n, --configName  Name of the typeorm config file (json or js).  [default: ""]
>   -c, --connection  Name of the typeorm connection                 [default: ""]
>   -r, --root        Path to your typeorm config file
>                   [default: "C:\Users\richoandika\tmp\nestjs"]
>   --seed, -s        Specific seed class to run.
> 
> TypeError: Cannot read properties of undefined (reading 'name')
>     at Object.<anonymous> (C:\Users\richoandika\tmp\nestjs\node_modules\typeorm-seeding\src\commands\seed.command.ts:92:49)
>     at step (C:\Users\richoandika\tmp\nestjs\node_modules\tslib\tslib.js:143:27)
>     at Object.next (C:\Users\richoandika\tmp\nestjs\node_modules\tslib\tslib.js:124:57)
>     at fulfilled (C:\Users\richoandika\tmp\nestjs\node_modules\tslib\tslib.js:114:62)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

My bad, solved by clean the cache and adding `./` in module path

**Comment by richoandika** [comment]
@andi-faizal94 Hi,
I think there's your problem bro
![image](https://user-images.githubusercontent.com/24300318/163391069-bfaa7237-9799-4330-bcb7-014c65ade1b3.png)
just adding `./` into module path like `import { UserEntity } from './../entities/user.entity'`

**Comment by richoandika** [comment]
@andi-faizal94 Hi,
I think there's your problem bro
![image](https://user-images.githubusercontent.com/24300318/163391069-bfaa7237-9799-4330-bcb7-014c65ade1b3.png)
just adding `./` into module path like `import { UserEntity } from './../entities/user.entity'`

**Comment by richoandika** [comment]
@andi-faizal94 Hi,
I think there's your problem bro
![image](https://user-images.githubusercontent.com/24300318/163391069-bfaa7237-9799-4330-bcb7-014c65ade1b3.png)
just adding `./` into path of module like `import { UserEntity } from './../entities/user.entity'`
