### ISSUE TITLE
TypeError: this.subQuery is not a function

### ISSUE THREAD

**Issue by brunoti** [w3tecch/typeorm-seeding#53]
I don't really know what I am doing wrong, can you help me?

This is the complete output:

```
 yarn ts-node -r tsconfig-paths/register ../../node_modules/typeorm-seeding/dist/cli.js seed
yarn run v1.22.0
$ /Volumes/SD/Users/bruno/Projects/corona-down/node_modules/.bin/ts-node -r tsconfig-paths/register ../../node_modules/typeorm-seeding/dist/cli.js seed
🌱 TypeORM Seeding v1.4.4
✔ ORM Config loaded
✔ Factories are imported
✔ Seeders are imported
✔ Database connected
✖ Could not run the seed CreateApplicationToken!
TypeError: this.subQuery is not a function
    at InsertQueryBuilder.QueryBuilder.createFromAlias (/Volumes/SD/Users/bruno/Projects/corona-down/src/query-builder/QueryBuilder.ts:551:131)
    at InsertQueryBuilder.into (/Volumes/SD/Users/bruno/Projects/corona-down/src/query-builder/InsertQueryBuilder.ts:158:32)
    at CreateApplicationToken.run (/Volumes/SD/Users/bruno/Projects/corona-down/packages/backend/src/database/seeds/CreateApplicationToken.ts:11:8)
    at /Volumes/SD/Users/bruno/Projects/corona-down/node_modules/typeorm-seeding/src/typeorm-seeding.ts:48:17
    at step (/Volumes/SD/Users/bruno/Projects/corona-down/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Volumes/SD/Users/bruno/Projects/corona-down/node_modules/tslib/tslib.js:120:57)
    at /Volumes/SD/Users/bruno/Projects/corona-down/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Volumes/SD/Users/bruno/Projects/corona-down/node_modules/tslib/tslib.js:109:16)
    at Object.exports.runSeeder (/Volumes/SD/Users/bruno/Projects/corona-down/node_modules/typeorm-seeding/src/typeorm-seeding.ts:46:57)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is my seeder:

```typescript
import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';
import { ApplicationToken } from '@backend/entities/ApplicationToken';
import uniqueString = require('unique-string');

export default class CreateApplicationToken implements Seeder {
  public async run(_factory: Factory, connection: Connection): Promise<void> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(ApplicationToken)
      .values([
        { token: uniqueString() },
      ])
      .execute();
  }
}
```

**Comment by hirsch88** [comment]
Hi @brunoti 
Could you please provide me your entity `ApplicationToken` for a full analysis.

**Comment by eranshmil** [comment]
This also happened to me, fixed that by setting the `TYPEORM_ENTITIES` environment variable.

**Comment by NMontilva** [comment]
I'm using ormconfig.json and I'm getting the same error as @brunoti 
I already set the entities variable in the .json and nothing. Same error

Here is my ormconfig.json

`{
  "type": "mysql",
  "host": "localhost",
  "port": 3306,
  "username": "a_username",
  "password": "a_password",
  "database": "a_db",
  "entities": ["entity/*.ts","dist/**/*.entity{.ts,.js}"],
  "synchronize": true,
  "seeds": ["src/database/seeds/**/*.seed.ts"]
}`

**Comment by hirsch88** [comment]
Hi @NMontilva 

Sure the path to your entites is correct? 

`"entity/*.ts"`  should this be `"src/**/*.entity{.ts,.js}"`

**Comment by NMontilva** [comment]
Hello @hirsch88 

Thank you! That was it.

**Comment by ahmedNY** [comment]
I had the same issue

**Comment by davicedraz** [comment]
Relatable, exactly the same error here!

maratona.entity.ts

```typescript
import { Entity, Column, CreateDateColumn, PrimaryGeneratedColumn } from 'typeorm';

@Entity({ name: 'maratonas' })
export class Maratona {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  title: string;

  @Column()
  date: Date;

  @CreateDateColumn()
  created_at?: Date;
}
```

maratona.seed.ts

```typescript
import { Connection } from 'typeorm';
import { Factory, Seeder } from 'typeorm-seeding';

import { Maratona } from '../entities/maratona.entity';

export default class CreateUsers implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    return await connection
      .createQueryBuilder()
      .insert()
      .into(Maratona)
      .values([
        { title: 'Full Cycle: Arquitetura e Estudo de Caso', date: `${new Date('04/05/2020')}` },
        { title: 'Ecossistema JS com Diego da Rocketseat', date: `${new Date('04/05/2020')}` },
        { title: 'Microsserviço Live Manager e Comunicação', date: `${new Date('05/05/2020')}` },
        {
          title: 'Skills de um Dev Full Cycle com Rodrigo Branas e Henrique Bastos',
          date: `${new Date('05/05/2020')}`,
        },
        { title: 'Realizando Streaming com Websockets e WebRTC', date: `${new Date('05/05/2020')}` },
        { title: 'Tempo Real na Web', date: `${new Date('06/05/2020')}` },
        { title: 'Microsserviços de Chat e CodeBot', date: `${new Date('07/05/2020')}` },
        { title: 'gRPC na Prática', date: `${new Date('07/05/2020')}` },
        { title: 'CI / CD e Tipos de Deploy s', date: `${new Date('08/05/2020')}` },
        { title: 'Service Mesh com Istio e Kiali', date: `${new Date('09/05/2020')}` },
        { title: 'Kafka com Elastic Stack', date: `${new Date('09/05/2020')}` },
        { title: 'Dashboards realtime com RabbitMQ e Elastic Stack', date: `${new Date('11/05/2020')}` },
        { title: 'Abertura das Matrículas', date: `${new Date('11/05/2020')}` },
      ])
      .execute();
  }
}
```

.env

```bash
TYPEORM_CONNECTION=sqlite
TYPEORM_DATABASE=database.sqlite
TYPEORM_ENTITIES=src/**/*.entity{.ts,.js}
TYPEORM_MIGRATIONS=src/database/migrations/**/*.ts
TYPEORM_MIGRATIONS_DIR=src/database/migrations
TYPEORM_SEEDING_FACTORIES=src/database/factories/**/*{.ts,.js}
TYPEORM_SEEDING_SEEDS=src/database/seeds/**/*{.ts,.js}
```

**Comment by hirsch88** [comment]
The error `TypeError: this.subQuery is not a function` is because typeorm could not find any entities.

**Comment by nrctkno** [comment]
In addition to the path in ormconfig, check if your entities were imported in your module.

**Comment by aphofstede** [comment]
For posterity: If you're using e.g. entities/index.ts to list your entities, make sure it is being exported there.

**Comment by pehrlich-arbor** [comment]
In my case, I had used relative import paths in one file. This caused nodejs to cache different versions of my imported entity. When TypeORM calls `findMetadata` internally to see if if it can process the query, it does an object-based equality match, which was therefore failing due to my entities being imported from different places :-S
