### ISSUE TITLE
jsonb type in column throws error

### ISSUE THREAD

**Issue by humbertowoody** [w3tecch/typeorm-seeding#9]
Hi! I am unable to seed a `jsonb` type of field on a PostgreSQL 10.0 database. The error does not occur during insertion and update queries, only on seeding. This is my model:

```typescript
import { IsNotEmpty } from 'class-validator';
import {
    Column, CreateDateColumn, Entity, ManyToOne, PrimaryColumn, UpdateDateColumn
} from 'typeorm';

import { Session } from './Session';

@Entity()
export class Resource {
    @PrimaryColumn('uuid')
    public id: string;

    @IsNotEmpty()
    @Column()
    public source: string;

    @IsNotEmpty()
    @Column({ type: 'jsonb'}) // Tried with `jsonb` by itself and same error.
    public data: any;

    @UpdateDateColumn({ name: 'updated_at' })
    public updatedAt: Date;

    @CreateDateColumn({ name: 'created_at' })
    public createdAt: Date;

    @ManyToOne(type => Session, session => session.resources)
    public session: Session;
}
```

And here is my factory:

```typescript
import * as Faker from 'faker';
import { define } from 'typeorm-seeding';
import * as uuid from 'uuid';

import { Resource } from '../../../src/api/models/Resource';

define(Resource, (faker: typeof Faker) => {
    const source = faker.company.companyName();

    const resource = new Resource();
    resource.id = uuid.v1();
    resource.source = source;
    // resource.data = 12; // Works ok, but I need an object!
    // resource.data = "hello my github friends"; // Works ok, but I need an object!
    // resource.data = new Object({ foo: 'bar' }); // Does not work!
    resource.data = { foo: 'bar' }; // Does not work either!
    return resource;
});
```

Which throws a: 

```txt
Could not run seed  Error: Could not save entity
    at EntityFactory.<anonymous> (/Users/humbertowoody/Proyectos/VR3/fetchbug-api/node_modules/typeorm-seeding/dist/typeorm-seeding.js:102:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/humbertowoody/Proyectos/VR3/fetchbug-api/node_modules/typeorm-seeding/dist/typeorm-seeding.js:30:65)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Is there a problem on seeding `jsonb` type of columns? Thanks in advance!

**Comment by maxime-lenne** [comment]
Hi! I have the same issue wit Geojson. The type of my column is Point and typeorm-seeding try to make this sub entity in resolveEntity function.
